# Generated by Django 5.2.9 on 2025-12-25 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('BASE', 'Base'), ('DEVELOPER', 'Developer'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('allowed_namespaces', models.JSONField(default=list)),
                ('monthly_api_limit', models.IntegerField()),
                ('max_records', models.IntegerField()),
                ('max_records_per_query', models.IntegerField()),
                ('can_create_records', models.BooleanField(default=False)),
                ('can_update_records', models.BooleanField(default=False)),
                ('can_delete_records', models.BooleanField(default=False)),
                ('can_create_custom_objects', models.BooleanField(default=False)),
                ('max_custom_objects', models.IntegerField(default=0)),
                ('allow_filters', models.BooleanField(default=False)),
                ('allow_sorting', models.BooleanField(default=False)),
                ('allow_bulk_operations', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform_owned', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=50)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('QA', 'Qa'), ('USER', 'User'), ('DEVELOPER', 'Developer'), ('PRODUCT MANAGER', 'Product Manager'), ('TEAM LEAD', 'Team Lead')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_ip', models.GenericIPAddressField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureUsageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform_owned', models.BooleanField(default=False)),
                ('event_id', models.CharField(max_length=30, unique=True)),
                ('feature_name', models.CharField(max_length=100)),
                ('api_calls_made', models.PositiveIntegerField()),
                ('data_volume_mb', models.FloatField()),
                ('success_rate', models.FloatField(help_text='Percentage value')),
                ('throttled', models.BooleanField(default=False)),
                ('client_app', models.CharField(max_length=50)),
                ('event_timestamp', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform_owned', models.BooleanField(default=False)),
                ('order_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking')], max_length=20)),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=20)),
                ('transaction_reference', models.CharField(max_length=50)),
                ('is_refundable', models.BooleanField(default=False)),
                ('order_date', models.DateField()),
                ('discount_applied', models.FloatField(help_text='Percentage value')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform_owned', models.BooleanField(default=False)),
                ('product_id', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_count', models.PositiveIntegerField()),
                ('product_rating', models.FloatField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform_owned', models.BooleanField(default=False)),
                ('log_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('service_name', models.CharField(max_length=50)),
                ('log_level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('request_path', models.CharField(max_length=255)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('response_time_ms', models.PositiveIntegerField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('api_calls_today', models.PositiveIntegerField(default=0)),
                ('api_calls_limit', models.PositiveIntegerField(default=25)),
                ('api_calls_used', models.IntegerField(default=0)),
                ('records_used', models.IntegerField(default=0)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
