# Generated by Django 5.2.9 on 2025-12-25 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_reset_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 25, 8, 1, 35, 919376, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='LastName', max_length=25),
        ),
    ]
