# Generated by Django 5.2.9 on 2025-12-25 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_api_reset_at_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_calls_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='api_calls_today',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='api_reset_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 25, 8, 17, 5, 638265, tzinfo=datetime.timezone.utc)),
        ),
    ]
