# Generated by Django 5.2.9 on 2025-12-25 10:58

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_api_calls_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='api_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
