# Generated by Django 5.2.9 on 2025-12-25 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productcatalog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productcatalog',
            constraint=models.UniqueConstraint(fields=('user', 'product_id'), name='unique_product_per_user'),
        ),
    ]
