# Generated by Django 5.2.9 on 2025-12-25 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productcatalog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcatalog',
            name='unique_product_per_user',
        ),
        migrations.RemoveField(
            model_name='productcatalog',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='productcatalog',
            constraint=models.UniqueConstraint(fields=('created_by', 'product_id'), name='unique_product_per_user'),
        ),
    ]
