# Generated by Django 5.2.9 on 2025-12-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_productcatalog_unique_product_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featureusageanalytics',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=14, null=True, unique=True),
        ),
    ]
