# Generated by Django 5.2.9 on 2025-12-25 12:16

import random
from django.db import migrations

def generate_public_id():
    return "".join(str(random.randint(0, 9)) for _ in range(14))

def backfill_public_id(apps, schema_editor):
    CustomerProfile = apps.get_model("core", "CustomerProfile")

    for obj in CustomerProfile.objects.filter(public_id__isnull=True):
        while True:
            candidate = generate_public_id()
            if not CustomerProfile.objects.filter(public_id=candidate).exists():
                obj.public_id = candidate
                obj.save(update_fields=["public_id"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customerprofile_public_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_public_id),
    ]
