# Generated by Django 5.2.9 on 2025-12-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='featureusageanalytics',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=14, unique=True),
        ),
    ]
