# Generated by Django 5.2.9 on 2025-12-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customerprofile_first_name_customerprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='featureusageanalytics',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='featureusageanalytics',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='productcatalog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='productcatalog',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='last_name',
        ),
    ]
