# Generated by Django 5.2.9 on 2025-12-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_customerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='user_ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
