# Generated by Django 5.2.9 on 2025-12-25 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_systemlog_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='log_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
