# Generated by Django 5.2.9 on 2025-12-28 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_is_email_verified_emailverificationtoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('api_name', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('max_records', models.PositiveIntegerField(default=1000)),
                ('allow_api_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'api_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomObjectRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_api_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_api_name', models.CharField(max_length=50)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('value_number', models.BigIntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='core.customobjectrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('api_name', models.SlugField()),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('EMAIL', 'Email'), ('JSON', 'JSON')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_indexed', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('regex', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.customobject')),
            ],
            options={
                'unique_together': {('custom_object', 'api_name')},
            },
        ),
    ]
