# Generated by Django 5.2.9 on 2025-12-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customobject_customobjectrecord_customfieldvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
